### ISSUE TITLE
Options Page Show Times Description duplicated with Extensible Binding Warnings

### ISSUE THREAD

**Issue by Hankych** [hapifhir/org.hl7.fhir.validator-wrapper#102]
Update the description of Show Times (showTimes), right now it has the same description as Extensible Binding Warnings.

**Comment by dotasek** [comment]
From the documentation, it looks like both the `showTimes` and the description are incorrect.

https://confluence.hl7.org/pages/viewpage.action?pageId=35718580#UsingtheFHIRValidator-ShowValidatorInternalTimes

The following is how it should appear:

```
Show Times (-show-times)

When selected the validator will produce a line in the output summarizing how long some internal processes took.
```
