### ISSUE TITLE
Error "Unable to connect to terminology server"

### ISSUE THREAD

**Issue by g-sasahara** [hapifhir/org.hl7.fhir.validator-wrapper#137]
When trying to run the validator, the request fails with the following response, for any content:
> "Unable to connect to terminology server. Use parameter '-tx n/a' to run without using terminology services to validate LOINC, SNOMED, ICD-X etc. Error = Error fetching the server's capability statement: Error reading Http Response: Error parsing JSON source: Unexpected char '<' in json stream at Line 1 (path=[null])"

This results in this visible error message.
> Cannot parse entered text as valid JSON/XML.

For reference, I tried FHIR examples along with these very basic contents.
> {}

and

> {  "resourceType": "Bundle",  "id": "xyz",  "type": "transaction",  "entry": [  ]}

**Comment by g-sasahara** [comment]
Works again.

**Comment by sonUTwelve** [comment]
Can you please tell me on how to run the 'org.hl7.fhir.validator-wrapper'? I'm currently just running as mentioned in the README i.e ./gradlew build and ./gradlew run . How do I pass the -tx n/a args ?
