### ISSUE TITLE
PulseOx validator error

### ISSUE THREAD

**Issue by jhrpcek** [hapifhir/org.hl7.fhir.validator-wrapper#161]
The validator is producing this error incorrectly for this profile:
https://hl7.org/fhir/us/core/STU3.1.1/StructureDefinition-us-core-pulse-oximetry.html

Used the example from that profile page:    https://hl7.org/fhir/us/core/STU3.1.1/Observation-satO2-fiO2.html

Error
Line: 104, Col:8
The Coding provided (http://unitsofmeasure.org#L/min) was not found in the value set 'Vital Signs Units' (http://hl7.org/fhir/ValueSet/ucum-vitals-common|4.0.1), and a code is required from this value set. (error message = The provided code 'http://unitsofmeasure.org#L/min' was not found in the value set 'http://hl7.org/fhir/ValueSet/ucum-vitals-common|4.0.1')

**Comment by grahamegrieve** [comment]
Why do you think that this is an error?

**Comment by jhrpcek** [comment]
Because "L/min" is what is defined in that profile as the "fixed" value to use for the component FlowRate's  valueQuantity.code

**Comment by grahamegrieve** [comment]
The validator is still correct. This is an issue with the way that profile is defined; you'll have to take it up on with the authors - probably https://chat.fhir.org/#narrow/stream/179190-united-states  is the best place to discuss
