### ISSUE TITLE
Validates against 4.5, even when I want 4.0.1

### ISSUE THREAD

**Issue by RichardTON** [hapifhir/org.hl7.fhir.validator-wrapper#54]
I get the error 

> Error Line: 36 Unrecognised property '@procedureCode'

when I validated the following. My example is 4.0.1 and the vlidator seems to use 4.5, even when I adjust the FHIR version in options.

{
  "resourceType": "ImagingStudy",
  "id": "echodicom-for-report",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p><b>Generated Narrative</b></p><p><b>identifier</b>: id: urn:oid:1.2.36.1.2001.1001.105.100007.30246.19789.3503430046</p><p><b>status</b>: available</p><p><b>modality</b>: <span title=\"{http://dicom.nema.org/resources/ontology/DCM US}\">Ultrasound</span></p><p><b>subject</b>: <a href=\"Patient-995138d0-b8bc-4bd9-b49d-d2d025d39ae7.html\">Generated Summary: IHI: 8003608000228437, Medicare Number: 29533070311, Medical Record Number: 2338172; Wei Zhang ; gender: male; birthDate: 1969-05-03</a></p><p><b>started</b>: 06/01/2019 9:45:00 AM</p><p><b>basedOn</b>: <a href=\"ServiceRequest-edbc04cd-3387-435c-bda7-6e1a837b2590.html\">Generated Summary: status: completed; intent: order; <span title=\"Codes: {http://snomed.info/sct 276341003}\">Cardiovascular investigation</span>; <span title=\"Codes: {http://snomed.info/sct 40701008}\">Echocardiography</span>; authoredOn: 05/01/2019 12:00:00 AM; <span title=\"Codes: \">Pre-chemotherapy</span></a></p><p><b>endpoint</b>: <a href=\"Endpoint-nsw-hospital-wadors.html\">Generated Summary: status: active; <span title=\"{http://terminology.hl7.org/CodeSystem/endpoint-connection-type dicom-wado-rs}\">DICOM WADO-RS</span>; name: NSW Hospital DICOM WADO-RS endpoint; <span title=\"Codes: \">DICOM WADO-RS</span>; payloadMimeType: application/dicom; address: http://www.health.nsw.example.org/nsw-hospital/wado-rs</a></p><p><b>procedureCode</b>: <span title=\"Codes: {http://loinc.org 42148-7}, {http://www.radlex.org RPID5656}, {http://snomed.info/sct 40701008}\">US Heart</span></p><p><b>reasonCode</b>: <span title=\"Codes: \">Pre-chemotherapy</span></p></div>"
  },
  "identifier": [
    {
      "system": "urn:dicom:uid",
      "value": "urn:oid:1.2.36.1.2001.1001.105.100007.30246.19789.3503430046"
    }
  ],
  "status": "available",
  "modality": [
    {
      "system": "http://dicom.nema.org/resources/ontology/DCM",
      "code": "US",
      "display": "Ultrasound"
    }
  ],
  "subject": {
    "reference": "Patient/995138d0-b8bc-4bd9-b49d-d2d025d39ae7"
  },
  "started": "2019-01-06T09:45:00+10:00",
  "basedOn": [
    {
      "reference": "ServiceRequest/edbc04cd-3387-435c-bda7-6e1a837b2590"
    }
  ],
  "endpoint": [
    {
      "reference": "Endpoint/nsw-hospital-wadors"
    }
  ],
  "procedureCode": [
    {
      "coding": [
        {
          "system": "http://loinc.org",
          "code": "42148-7",
          "display": "US Heart"
        },
        {
          "system": "http://www.radlex.org",
          "code": "RPID5656",
          "display": "US Heart"
        },
        {
          "system": "http://snomed.info/sct",
          "code": "40701008",
          "display": "Echocardiography"
        }
      ]
    }
  ],
  "reasonCode": [
    {
      "text": "Pre-chemotherapy"
    }
  ]
}

**Comment by markiantorno** [comment]
Thanks for logging this.

It has been fixed.
