### ISSUE TITLE
Could not start

### ISSUE THREAD

**Issue by yunwwang** [hapifhir/org.hl7.fhir.validator-wrapper#90]
I am using MacBook with M1 chips.

when I start,

`./gradlew build` failed

Error:

> Task :kotlinNpmInstall FAILED
error Couldn't find package "core-js@3.9.1" required by "validator-wrapper@1.0.27-SNAPSHOT" on the "npm" registry.
Error: Couldn't find package "react-dom@17.0.1" required by "validator-wrapper@1.0.27-SNAPSHOT" on the "npm" registry.

**Comment by dotasek** [comment]
I have not been able to replicate this.

On my Mac M1, I clone the repository, then

```shell
./gradlew build
./gradlew run
```

It's possible that a temporary network issue prevented the download of some dependencies. One thing I have had to do on occasion is `./gradlew build --refresh-dependencies` to force a refresh if something went wrong with a download.

If things are particularly bad, I have also resorted to this: `rm -rf $HOME/.gradle/caches/` but I think I've only had to do that once.
